// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chirpyred.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const enableChirpyRedByID = `-- name: EnableChirpyRedByID :exec
UPDATE users
SET is_chirpy_red = TRUE
WHERE id = $1
`

func (q *Queries) EnableChirpyRedByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, enableChirpyRedByID, id)
	return err
}
